# Generated by Django 5.0.3 on 2024-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimodelo',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mimodelo',
            name='movil',
            field=models.IntegerField(null=True),
        ),
    ]
